language: python
sudo: false
dist: xenial
python: "3.7"

stages:
  - test

install:
  - pip install pipenv
  - pipenv install --dev

script: skip

jobs:
  include:
    - stage: test
    - script:
      - pipenv run coverage run -m unittest discover
      - pipenv run coverage report
